#!/bin/bash
# Checkout all spec files into subdirectories under the current directory.
# This is needed to bootstrap a spec directory. To update them later, run
# update-all-specs and checkout-new-specs, which may be slightly more
# efficient. That won't delete directories that were removed, however.
set -e
#export BASE_SVN='svn+ssh://svn.mageia.org/svn/packages/cauldron/'
export BASE_SVN='svn://svn.mageia.org/svn/packages/cauldron/'
svn ls "$BASE_SVN" >all-specs.lst
echo $(wc -l all-specs.lst) packages to download
xargs -n1 -i{} -P4 sh -c "svn co '$BASE_SVN'{}current/SPECS {}" <all-specs.lst
