#!/bin/bash
# Checkout all spec files into subdirectories under the current directory.
# This is needed to bootstrap a spec directory. To update them later, run
# update-all-specs and checkout-new-specs, which should be slightly more
# efficient.
set -e
#export BASE_SVN='svn+ssh://svn.mageia.org/svn/packages/cauldron/'
export BASE_SVN='svn://svn.mageia.org/svn/packages/cauldron/'
readonly SPECSLIST="$(mktemp)"
trap 'rm -f "${SPECSLIST}"' EXIT

svn ls "$BASE_SVN" >"${SPECSLIST}"
echo $(wc -l "${SPECSLIST}" | awk '{print $1}') packages to check/download
xargs -n1 -i{} -P4 sh -c "svn co '$BASE_SVN'{}current/SPECS {}" <"${SPECSLIST}"
