#!/bin/bash
# Greps through .spec files
#
# Copyright © 2020–2022 Daniel Fandrich.
# This program is free software; you can redistribute it and/or modify
# Licensed under GNU General Public License 2.0 or later.
# Some rights reserved. See COPYING.

readonly SPEC_TREE="${SPEC_TREE:-.}"
find "${SPEC_TREE}" -name '*.spec' -print0 | xargs -0 -n32 grep -P "$@"
